# Generated by Django 5.0 on 2023-12-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_proprietate', models.CharField(choices=[('apartamente', 'Apartamente'), ('case/vile', 'Case/Vile'), ('terenuri', 'Terenuri')], max_length=30)),
                ('tip_vanzare', models.CharField(choices=[('de vanzare', 'De vanzare'), ('de inchiriat', 'De inchiriat')], max_length=30)),
                ('titul_anunt', models.CharField(max_length=80)),
                ('poze', models.ImageField(null=True, upload_to='media/')),
                ('suprafata_utila', models.CharField(max_length=10)),
                ('pret', models.CharField(max_length=30)),
                ('localizare', models.CharField(max_length=80)),
                ('descriere', models.TextField(max_length=500)),
            ],
        ),
    ]
