# Generated by Django 5.0 on 2023-12-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createPost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunt',
            name='tip_anunt',
            field=models.CharField(choices=[('C0', 'Comision 0'), ('AR', 'Ansamblu Rezidential'), ('AI', 'Agentii Imobiliare')], default='C0', max_length=2),
        ),
    ]
