# Generated by Django 5.0 on 2023-12-16 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createPost', '0002_anunt_tip_anunt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promovare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metoda_de_promovare', models.CharField(choices=[('SP', 'Promovare Simpla'), ('PP', 'Promovare Premium'), ('TL', 'Top Listing')], default='SP', max_length=2)),
                ('anunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createPost.anunt')),
            ],
        ),
    ]
