# Generated by Django 5.0 on 2023-12-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createPost', '0003_promovare'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunt',
            name='numar_carte_funciara',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
