# Generated by Django 5.0 on 2023-12-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createPost', '0004_anunt_numar_carte_funciara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunt',
            name='numar_carte_funciara',
            field=models.CharField(max_length=15),
        ),
    ]
