# Generated by Django 5.0 on 2024-02-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createPost', '0006_alter_anunt_tip_anunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunt',
            name='numar_bai',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anunt',
            name='numar_camere',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
