# Generated by Django 5.0 on 2023-12-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localitate', models.CharField(max_length=30)),
                ('tip_proprietate', models.CharField(choices=[('apartamente', 'Apartamente'), ('case/vile', 'Case/Vile'), ('terenuri', 'Terenuri')], max_length=30)),
                ('tip_achizitie', models.CharField(choices=[('de vanzare', 'De vanzare'), ('de inchiriat', 'De inchiriat')], max_length=30)),
            ],
        ),
    ]
