# Generated by Django 5.0 on 2023-12-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='categorie',
            field=models.CharField(choices=[('C0', 'Comision 0'), ('AR', 'Ansamblu Rezidential'), ('AI', 'Agentii Imobiliare')], default='C0', max_length=30),
        ),
    ]
